baseURL = "http://example.org/"
languageCode = "en-us"
title = "Seputar Teknologi"
theme = "mainroad"
dateformat = "2021-01-02" 

[Author]
    name = "Ananda Zulvansyah Putra"
    bio = "mahasiswa kupu-kupu"
    avatar = "img/avatar.png"

[Params]
    subtitle = "berisi segala hal yang berbau teknologi"
    copyright = "Ananda Zulvansyah Putra"
    authorbox = true
    readmore = true
    toc = true
    pager = true
    dateformat = "DD-MM-YYYY"

[Params.sidebar] 
    home = "right"
    list = "left"
    widgets = ["search", "recent", "categories", "taglist", "social", "languages"]

[Params.widgets]
  recent_num = 5 

[Params.widgets.social]
    github = "azurasan/seputar-teknologi"

[menu]
    [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
    [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 2